[2025-05-03T15:05:52.864+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-03T15:05:52.882+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.detect_language manual__2025-05-03T15:04:48.168882+00:00 [queued]>
[2025-05-03T15:05:52.891+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.detect_language manual__2025-05-03T15:04:48.168882+00:00 [queued]>
[2025-05-03T15:05:52.893+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-05-03T15:05:52.903+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): detect_language> on 2025-05-03 15:04:48.168882+00:00
[2025-05-03T15:05:52.916+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5260) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-03T15:05:52.919+0000] {standard_task_runner.py:72} INFO - Started process 5275 to run task
[2025-05-03T15:05:52.919+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'detect_language', 'manual__2025-05-03T15:04:48.168882+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpckc_f55z']
[2025-05-03T15:05:52.920+0000] {standard_task_runner.py:105} INFO - Job 334: Subtask detect_language
[2025-05-03T15:05:52.962+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.detect_language manual__2025-05-03T15:04:48.168882+00:00 [running]> on host 8280c28b7f0f
[2025-05-03T15:05:53.040+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='detect_language' AIRFLOW_CTX_EXECUTION_DATE='2025-05-03T15:04:48.168882+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-03T15:04:48.168882+00:00'
[2025-05-03T15:05:53.042+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-03T15:05:53.043+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-03T15:05:53.043+0000] {logging_mixin.py:190} INFO - Current task name:detect_language state:running start_date:2025-05-03 15:05:52.883035+00:00
[2025-05-03T15:05:53.044+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-03T15:05:53.044+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-03T15:05:53.053+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-03T15:05:53.060+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 207, in detect_language_reviews
    cur.execute("SELECT review_text, id FROM review.raw_reviews WHERE language IS NULL;")
psycopg2.errors.UndefinedColumn: column "language" does not exist
LINE 1: ...ECT review_text, id FROM review.raw_reviews WHERE language I...
                                                             ^

[2025-05-03T15:05:53.076+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-03T15:05:53.077+0000] {logging_mixin.py:190} INFO - Task start:2025-05-03 15:05:52.883035+00:00 end:2025-05-03 15:05:53.076471+00:00 duration:0.193436
[2025-05-03T15:05:53.078+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): detect_language> dag:<DAG: google_maps_reviews> dagrun:<DagRun google_maps_reviews @ 2025-05-03 15:04:48.168882+00:00: manual__2025-05-03T15:04:48.168882+00:00, state:running, queued_at: 2025-05-03 15:04:48.193059+00:00. externally triggered: True>
[2025-05-03T15:05:53.078+0000] {logging_mixin.py:190} INFO - Failure caused by column "language" does not exist
LINE 1: ...ECT review_text, id FROM review.raw_reviews WHERE language I...
                                                             ^
[2025-05-03T15:05:53.079+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=google_maps_reviews, task_id=detect_language, run_id=manual__2025-05-03T15:04:48.168882+00:00, execution_date=20250503T150448, start_date=20250503T150552, end_date=20250503T150553
[2025-05-03T15:05:53.104+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-03T15:05:53.105+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 334 for task detect_language (column "language" does not exist
LINE 1: ...ECT review_text, id FROM review.raw_reviews WHERE language I...
                                                             ^
; 5275)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 207, in detect_language_reviews
    cur.execute("SELECT review_text, id FROM review.raw_reviews WHERE language IS NULL;")
psycopg2.errors.UndefinedColumn: column "language" does not exist
LINE 1: ...ECT review_text, id FROM review.raw_reviews WHERE language I...
                                                             ^

[2025-05-03T15:05:53.134+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-03T15:05:53.158+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-03T15:05:53.160+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
