[2025-05-06T16:44:23.880+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-06T16:44:23.938+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv scheduled__2025-05-05T00:00:00+00:00 [queued]>
[2025-05-06T16:44:23.965+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.export_to_csv scheduled__2025-05-05T00:00:00+00:00 [queued]>
[2025-05-06T16:44:23.983+0000] {taskinstance.py:2867} INFO - Starting attempt 13 of 14
[2025-05-06T16:44:24.015+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): export_to_csv> on 2025-05-05 00:00:00+00:00
[2025-05-06T16:44:24.035+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4163) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-06T16:44:24.040+0000] {standard_task_runner.py:72} INFO - Started process 4185 to run task
[2025-05-06T16:44:24.041+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'export_to_csv', 'scheduled__2025-05-05T00:00:00+00:00', '--job-id', '564', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpxdw5_3z5']
[2025-05-06T16:44:24.043+0000] {standard_task_runner.py:105} INFO - Job 564: Subtask export_to_csv
[2025-05-06T16:44:24.157+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.export_to_csv scheduled__2025-05-05T00:00:00+00:00 [running]> on host 8280c28b7f0f
[2025-05-06T16:44:24.376+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='export_to_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T00:00:00+00:00'
[2025-05-06T16:44:24.382+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-06T16:44:24.384+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-06T16:44:24.385+0000] {logging_mixin.py:190} INFO - Current task name:export_to_csv state:running start_date:2025-05-06 16:44:23.941006+00:00
[2025-05-06T16:44:24.386+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-06T16:44:24.388+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-06T16:44:24.409+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-06T16:44:24.421+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 82, in export_data
    cur.execute(query)
psycopg2.errors.GroupingError: column "rr.review_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 12:             rr.review_date,
                     ^

[2025-05-06T16:44:24.466+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-06T16:44:24.468+0000] {logging_mixin.py:190} INFO - Task start:2025-05-06 16:44:23.941006+00:00 end:2025-05-06 16:44:24.464628+00:00 duration:0.523622
[2025-05-06T16:44:24.469+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): export_to_csv> dag:<DAG: google_maps_reviews> dagrun:<DagRun google_maps_reviews @ 2025-05-05 00:00:00+00:00: scheduled__2025-05-05T00:00:00+00:00, state:running, queued_at: 2025-05-06 16:40:20.693086+00:00. externally triggered: False>
[2025-05-06T16:44:24.470+0000] {logging_mixin.py:190} INFO - Failure caused by column "rr.review_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 12:             rr.review_date,
                     ^
[2025-05-06T16:44:24.471+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=google_maps_reviews, task_id=export_to_csv, run_id=scheduled__2025-05-05T00:00:00+00:00, execution_date=20250505T000000, start_date=20250506T164423, end_date=20250506T164424
[2025-05-06T16:44:24.551+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-06T16:44:24.552+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 564 for task export_to_csv (column "rr.review_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 12:             rr.review_date,
                     ^
; 4185)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 82, in export_data
    cur.execute(query)
psycopg2.errors.GroupingError: column "rr.review_date" must appear in the GROUP BY clause or be used in an aggregate function
LINE 12:             rr.review_date,
                     ^

[2025-05-06T16:44:24.583+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-06T16:44:24.636+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-06T16:44:24.644+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
