[2025-05-02T19:12:45.469+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-02T19:12:45.520+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-02T18:59:46.705410+00:00 [queued]>
[2025-05-02T19:12:45.544+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: google_maps_reviews.model_data manual__2025-05-02T18:59:46.705410+00:00 [queued]>
[2025-05-02T19:12:45.563+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-05-02T19:12:45.595+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): model_data> on 2025-05-02 18:59:46.705410+00:00
[2025-05-02T19:12:45.613+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=891) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T19:12:45.617+0000] {standard_task_runner.py:72} INFO - Started process 906 to run task
[2025-05-02T19:12:45.616+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'google_maps_reviews', 'model_data', 'manual__2025-05-02T18:59:46.705410+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/***dag.py', '--cfg-path', '/tmp/tmpza47nilj']
[2025-05-02T19:12:45.619+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask model_data
[2025-05-02T19:12:45.714+0000] {task_command.py:467} INFO - Running <TaskInstance: google_maps_reviews.model_data manual__2025-05-02T18:59:46.705410+00:00 [running]> on host 6ca499d7a39a
[2025-05-02T19:12:45.901+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='google_maps_reviews' AIRFLOW_CTX_TASK_ID='model_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T18:59:46.705410+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T18:59:46.705410+00:00'
[2025-05-02T19:12:45.904+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-05-02T19:12:45.905+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-05-02T19:12:45.906+0000] {logging_mixin.py:190} INFO - Current task name:model_data state:running start_date:2025-05-02 19:12:45.522720+00:00
[2025-05-02T19:12:45.907+0000] {logging_mixin.py:190} INFO - Dag name:google_maps_reviews and current dag run status:running
[2025-05-02T19:12:45.908+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-05-02T19:12:45.926+0000] {base.py:84} INFO - Retrieving connection 'postgres_defaut'
[2025-05-02T19:12:45.936+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 118, in model_data
    raise e
  File "/opt/airflow/dags/storeData.py", line 113, in model_data
    cur.execute(populate_dim_sql)
psycopg2.errors.ObjectNotInPrerequisiteState: cannot insert into view "dim_bank"
DETAIL:  Views containing DISTINCT are not automatically updatable.
HINT:  To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.

[2025-05-02T19:12:45.959+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-05-02T19:12:45.960+0000] {logging_mixin.py:190} INFO - Task start:2025-05-02 19:12:45.522720+00:00 end:2025-05-02 19:12:45.958720+00:00 duration:0.436
[2025-05-02T19:12:45.961+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): model_data> dag:<DAG: google_maps_reviews> dagrun:<DagRun google_maps_reviews @ 2025-05-02 18:59:46.705410+00:00: manual__2025-05-02T18:59:46.705410+00:00, state:running, queued_at: 2025-05-02 18:59:46.754929+00:00. externally triggered: True>
[2025-05-02T19:12:45.962+0000] {logging_mixin.py:190} INFO - Failure caused by cannot insert into view "dim_bank"
DETAIL:  Views containing DISTINCT are not automatically updatable.
HINT:  To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.
[2025-05-02T19:12:45.963+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=google_maps_reviews, task_id=model_data, run_id=manual__2025-05-02T18:59:46.705410+00:00, execution_date=20250502T185946, start_date=20250502T191245, end_date=20250502T191245
[2025-05-02T19:12:46.009+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-05-02T19:12:46.010+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 150 for task model_data (cannot insert into view "dim_bank"
DETAIL:  Views containing DISTINCT are not automatically updatable.
HINT:  To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.
; 906)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storeData.py", line 118, in model_data
    raise e
  File "/opt/airflow/dags/storeData.py", line 113, in model_data
    cur.execute(populate_dim_sql)
psycopg2.errors.ObjectNotInPrerequisiteState: cannot insert into view "dim_bank"
DETAIL:  Views containing DISTINCT are not automatically updatable.
HINT:  To enable inserting into the view, provide an INSTEAD OF INSERT trigger or an unconditional ON INSERT DO INSTEAD rule.

[2025-05-02T19:12:46.037+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-02T19:12:46.093+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T19:12:46.107+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
